version: '3.8'

services:
  rest-api-shop:
    build: ./
    command: ./wait-for-postgres.sh db ./rest-api-shop
    ports:
     - 8080:8080
    depends_on:
     - db 
    environment:
     - DB_PASSWORD=qwerty


  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
     - 5436:5432